apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/Spoon/OneDrive/Documents/School/2024-1 Spring/CSE356/CSE356_project/backup/"