services:
  next:
    container_name: next
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: next.access
        fluentd-async-connect: "true"
  tile-server:
    container_name: tile-server
    build:
      context: ./
      dockerfile: ./docker/tile-server.Dockerfile
    volumes:
      - osm-data:/data/database/
    ports:
      - "8080:80"
      - "5432:5432"
    environment:
      DOWNLOAD_PBF: https://grading.cse356.compas.cs.stonybrook.edu/data/new-york.osm.pbf
  fluentd:
    container_name: fluentd
    build:
      context: ./
      dockerfile: ./docker/fluentd.Dockerfile
    volumes:
      - ./logs/:/var/log/fluentd/
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    restart: always
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.4
    ports:
      - "9090:8080"
    environment:
      PBF_URL: https://grading.cse356.compas.cs.stonybrook.edu/data/new-york.osm.pbf
      NOMINATIM_PASSWORD: mysecretpassword
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
    shm_size: 64MB
    restart: always

volumes:
  tile-server-data:
  nominatim-data: