services:
  next:
    container_name: next
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.prod
    image: 127.0.0.1:5000/next
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: next.access
        fluentd-async-connect: "true"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager

  fluentd:
    container_name: fluentd
    build:
      context: ./
      dockerfile: ./docker/fluentd.Dockerfile
    image: 127.0.0.1:5000/fluentd
    volumes:
      - ./logs/:/var/log/fluentd/
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager

  tile-server:
    container_name: tile-server
    build:
      context: ./
      dockerfile: ./docker/tile-server.Dockerfile
    image: 127.0.0.1:5000/tile-server
    volumes:
      - osm-data:/data/database/
    ports:
      - "8080:80"
      - "5432:5432"
    environment:
      DOWNLOAD_PBF: https://grading.cse356.compas.cs.stonybrook.edu/data/new-york.osm.pbf
      THREADS: 2
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == tile-server
          
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.4
    ports:
      - "9090:8080"
    environment:
      PBF_URL: https://grading.cse356.compas.cs.stonybrook.edu/data/new-york.osm.pbf
      NOMINATIM_PASSWORD: mysecretpassword
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_AUTOVACUUM_WORK_MEM: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 512MB
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 2147483648
    shm_size: 64MB
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == nominatim

volumes:
  osm-data:
  nominatim-data: