services:
  next:
    container_name: next
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    depends_on:
      - fluentd
      - tile-server
      - nominatim
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: next.access
        fluentd-async-connect: "true"
    restart: always
  tile-server:
    image: overv/openstreetmap-tile-server
    volumes:
      - osm-data:/data/database/
    ports:
      - "8080:80"
      - "5432:5432"
    command: "run"
  fluentd:
    container_name: fluentd
    build:
      context: ./
      dockerfile: fluentd.Dockerfile
    volumes:
      - ./logs/:/var/log/fluentd/
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    restart: always
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.4
    ports:
        - "9090:8080"
    environment:
        PBF_PATH: /nominatim/data/new-york.osm.pbf
        NOMINATIM_PASSWORD: mysecretpassword
    volumes:
      - ./new-york.osm.pbf:/nominatim/data/new-york.osm.pbf
      - nominatim-data:/var/lib/postgresql/14/main
    shm_size: 64MB

volumes:
  osm-data:
  nominatim-data: