x-logging-options: &logging
  logging:
    driver: 'fluentd'
    options:
      tag: '{{.Name}}'
      fluentd-address: localhost:24224
      fluentd-async-connect: 'true'

volumes:
  osm-data:
  mongo-data:
  mongo-config:
  portainer_data:
  nominatim-data:

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/
      dockerfile: ./nginx.Dockerfile
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      - tile-server
      - search
    <<: *logging

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: ../docker/frontend.dev.Dockerfile
    image: frontend
    depends_on:
      - fluentd
      - backend
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: ../docker/backend.dev.Dockerfile
    image: backend
    volumes:
      - ./backend/routes:/app/routes
    depends_on:
      - tile-server
      - db
      - mongo
    restart: always
    <<: *logging

  tile-server:
    container_name: tile-server
    build:
      context: ./docker/
      dockerfile: ./tile.Dockerfile
    image: tile-server
    ports:
      - '8080:80'
    shm_size: 2gb
    restart: always

  # search:
  #   container_name: search_microservice
  #   build:
  #     context: ./search/
  #     dockerfile: ../docker/search.Dockerfile
  #   image: search
  #   ports:
  #     - '3003:80'
  #   restart: always
  search:
    container_name: nominatim
    image: mediagis/nominatim:4.0
    ports:
      - '3003:8080'
    environment:
      PBF_URL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf
      NOMINATIM_TOKENIZER: icu
      NOMINATIM_DATABASE_DSN: pgsql:dbname=nominatim;user=postgres;password=mysecretpassword;host=db;port=5432
      PGDATABASE: nominatim
      PGUSER: postgres
      PGPASSWORD: mysecretpassword
      PGHOST: db
      NOMINATIM_PASSWORD: mysecretpassword
      POSTGRES_SHARED_BUFFERS: 2GB # 25% of total memory
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_AUTOVACUUM_WORK_MEM: 2GB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 4GB
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
    shm_size: 256mb

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
      MONGO_INITDB_DATABASE: 'user'
    restart: always

  db:
    container_name: db
    build:
      context: ./docker/
      dockerfile: ./db.Dockerfile
    image: db
    volumes:
      - osm-data:/var/lib/postgresql/14/main
      - ./backup:/backup
    ports:
      - '5432:5432'
    shm_size: 2gb
    restart: always

  tile-cache:
    container_name: tile-cache
    image: memcached:latest
    command: '-m 512 -I 10m -v'

  fluentd:
    container_name: fluentd
    build:
      context: ./docker/
      dockerfile: ./fluentd.Dockerfile
    image: fluentd
    ports:
      - '24224:24224'
      - '24224:24224/udp'

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.19.4
    ports:
      - '9443:9443'
      - '8000:8000'
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
