services:
  # nginx:
  #   image: nginx:latest
  #   platform: linux/amd64

  fluentd:
    build:
      context: ./docker/
      dockerfile: ./fluentd.Dockerfile
    image: ktao87/cse356:fluentd
    platform: linux/amd64

  frontend:
    build:
      context: ./frontend/
      dockerfile: ../docker/frontend.prod.Dockerfile
    image: ktao87/cse356:frontend
    platform: linux/amd64

  backend:
    build:
      context: ./backend/
      dockerfile: ../docker/backend.prod.Dockerfile
    image: ktao87/cse356:backend
    platform: linux/amd64

  # mongo:
  #   image: mongo:latest
  #   platform: linux/amd64

  tile-server:
    build:
      context: ./docker/
      dockerfile: ./tile.Dockerfile
    image: ktao87/cse356:tile-server
    platform: linux/amd64

  # tile-cache:
  #   image: memcached:latest
  #   platform: linux/amd64

  search:
    container_name: search_microservice
    build:
      context: ./search/
      dockerfile: ../docker/search.Dockerfile
    image: ktao87/cse356:search
    platform: linux/amd64

  db:
    container_name: db
    build:
      context: ./docker/
      dockerfile: ./db.Dockerfile
    image: ktao87/cse356:db
    platform: linux/amd64

  # agent:
  #   image: portainer/agent:2.19.4
  #   platform: linux/amd64

  # portainer:
  #   image: portainer/portainer-ce:2.19.4
  #   platform: linux/amd64
