x-logging-options: &logging
  logging:
    driver: 'fluentd'
    options:
      tag: '{{.Name}}'
      fluentd-address: localhost:24224
      fluentd-async-connect: 'true'

volumes:
  osm-data:
  nominatim-data:
  routing-data:
  mongo-data:
  mongo-config:
  import-data:
  portainer_data:

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - frontend
      - backend
    <<: *logging

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: ../docker/frontend.dev.Dockerfile
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - fluentd
      - backend
    restart: always

  fluentd:
    container_name: fluentd
    build:
      context: ./docker/
      dockerfile: ./fluentd.Dockerfile
    volumes:
      - ./docker/fluent.conf:/fluentd/etc/fluent.conf
      - ./logs/:/var/log/fluentd/
    ports:
      - '24224:24224'
      - '24224:24224/udp'

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: ../docker/backend.dev.Dockerfile
    volumes:
      - ./backend/server.js:/app/server.js
      - ./backend/routes:/app/routes
    depends_on:
      - tile-server
      - nominatim
      - pgrouting
      - mongo
    restart: always
    <<: *logging

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
      MONGO_INITDB_DATABASE: 'user'
    restart: always

  tile-server:
    container_name: tile-server
    build:
      context: ./docker/
      dockerfile: ./tile-server.Dockerfile
    volumes:
      - osm-data:/data/database/
    ports:
      - '8080:80'
      - '5432:5432'
    environment:
      DOWNLOAD_PBF: https://grading.cse356.compas.cs.stonybrook.edu/data/us-northeast.osm.pbf
    shm_size: 256mb
    restart: always

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.4
    ports:
      - '9090:8080'
    environment:
      PBF_URL: https://grading.cse356.compas.cs.stonybrook.edu/data/us-northeast.osm.pbf
      NOMINATIM_PASSWORD: mysecretpassword
      POSTGRES_SHARED_BUFFERS: 2GB # 25% of total memory
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_AUTOVACUUM_WORK_MEM: 2GB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 4GB
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
    shm_size: 2gb

  pgrouting:
    container_name: pgrouting
    image: pgrouting/pgrouting:latest
    ports:
      - '5433:5432'
    volumes:
      - routing-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: routing
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      timeout: 5s
      retries: 10
    restart: always

  db-import:
    build:
      context: ./docker/
      dockerfile: ./db-import.Dockerfile
    container_name: db-import
    volumes:
      - import-data:/data
    restart: 'no'
    depends_on:
      pgrouting:
        condition: service_healthy

  glances:
    container_name: glances
    image: nicolargo/glances:latest-full
    restart: always
    pid: 'host'
    privileged: true
    ports:
      - 61208:61208
      - 61209:61209
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: America/New_York
      GLANCES_OPT: -C /glances/conf/glances.conf -w

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.19.4
    ports:
      - '9443:9443'
      - '8000:8000'
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
