services:
  reverse_proxy:
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: ../docker/frontend.dev.Dockerfile
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - fluentd
      - tile-server
      - nominatim
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: 127.0.0.1:24224
        tag: frontend
        fluentd-async-connect: 'true'
    restart: always

  fluentd:
    container_name: fluentd
    build:
      context: ./docker/
      dockerfile: ./fluentd.Dockerfile
    volumes:
      - ./logs/:/var/log/fluentd/
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: ../docker/backend.dev.Dockerfile
    volumes:
      - ./backend/server.js:/app/server.js
      - ./backend/routes:/app/routes
    depends_on:
      - tile-server
      - nominatim
      - mongo
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: 127.0.0.1:24224
        tag: backend
        fluentd-async-connect: 'true'
    restart: always

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
      MONGO_INITDB_DATABASE: 'user'

  tile-server:
    container_name: tile-server
    build:
      context: ./docker/
      dockerfile: ./tile-server.Dockerfile
    volumes:
      - osm-data:/data/database/
    ports:
      - '8080:80'
      - '5432:5432'
    environment:
      DOWNLOAD_PBF: https://grading.cse356.compas.cs.stonybrook.edu/data/us-northeast.osm.pbf
    shm_size: 192mb

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.4
    ports:
      - '9090:8080'
    environment:
      PBF_URL: https://grading.cse356.compas.cs.stonybrook.edu/data/us-northeast.osm.pbf
      NOMINATIM_PASSWORD: mysecretpassword
      POSTGRES_SHARED_BUFFERS: 2GB # 25% of total memory
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_AUTOVACUUM_WORK_MEM: 2GB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 4GB
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
    shm_size: 2gb

  pgrouting:
    container_name: pgrouting
    image: pgrouting/pgrouting:latest
    ports:
      - '5433:5432'
    volumes:
      - routing-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: routing
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      timeout: 5s
      retries: 10

  db-import:
    build:
      context: ./docker/
      dockerfile: ./db-import.Dockerfile
    container_name: db-import
    volumes:
      - import-data:/data
    restart: 'no'
    depends_on:
      pgrouting:
        condition: service_healthy

volumes:
  osm-data:
  nominatim-data:
  routing-data:
  mongo-data:
  mongo-config:
  import-data:
