services:
  next:
    container_name: next
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/app
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: next.access
        fluentd-async-connect: "true"
    restart: always
  tile-server:
    image: overv/openstreetmap-tile-server
    volumes:
      - osm-data:/data/database/
    ports:
      - "8080:80"
      - "5432:5432"
    command: "run"
  fluentd:
    container_name: fluentd
    build:
      context: ./
      dockerfile: fluentd.Dockerfile
    volumes:
      - ./logs/:/var/log/fluentd/
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    restart: always

volumes:
  osm-data:
    external: true