services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: ../docker/frontend.prod.Dockerfile
    image: 127.0.0.1:5000/next
    ports:
      - "80:3000"
    restart: always
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: frontend
        fluentd-async-connect: "true"
    deploy:
      placement:
        constraints:
          - node.role == manager

  fluentd:
    container_name: fluentd
    build:
      context: ./docker/
      dockerfile: ./fluentd.Dockerfile
    image: 127.0.0.1:5000/fluentd
    volumes:
      - ./logs/:/var/log/fluentd/
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: ../docker/backend.prod.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - tile-server
      - nominatim
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: backend
        fluentd-async-connect: "true"
    restart: always

  tile-server:
    container_name: tile-server
    build:
      context: ./docker/
      dockerfile: ./tile-server.Dockerfile
    image: 127.0.0.1:5000/tile-server
    volumes:
      - osm-data:/data/database/
    ports:
      - "8080:80"
    environment:
      DOWNLOAD_PBF: https://grading.cse356.compas.cs.stonybrook.edu/data/us-northeast.osm.pbf
      THREADS: 2
    deploy:
      placement:
        constraints:
          - node.role == worker
  fluentd:
    container_name: fluentd
    build:
      context: ./
      dockerfile: ./docker/fluentd.Dockerfile
    image: 127.0.0.1:5000/fluentd
    volumes:
      - ./logs/:/var/log/fluentd/
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.4
    environment:
      PBF_URL: https://grading.cse356.compas.cs.stonybrook.edu/data/us-northeast.osm.pbf
      NOMINATIM_PASSWORD: mysecretpassword
      POSTGRES_SHARED_BUFFERS: 2GB # 25% of total memory
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB 
      POSTGRES_AUTOVACUUM_WORK_MEM: 2GB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 4GB
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 4294967296 # half of total memory
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  osm-data:
  nominatim-data: