services:
  next:
    container_name: next
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - postgres
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: next.access
        fluentd-async-connect: "true"
  postgres:
    container_name: postgres
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
  fluentd:
    container_name: fluentd
    build:
      context: ./
      dockerfile: fluentd.Dockerfile
    volumes:
      - ./logs/:/var/log/fluentd/
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    restart: always