services:
  reverse_proxy:
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: ../docker/frontend.prod.Dockerfile
    image: 127.0.0.1:5000/next
    restart: always
    depends_on:
      - fluentd
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: 127.0.0.1:24224
        tag: frontend
        fluentd-async-connect: 'true'
    deploy:
      placement:
        constraints:
          - node.role == manager

  fluentd:
    container_name: fluentd
    build:
      context: ./docker/
      dockerfile: ./fluentd.Dockerfile
    image: 127.0.0.1:5000/fluentd
    volumes:
      - ./logs/:/var/log/fluentd/
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: ../docker/backend.prod.Dockerfile
    depends_on:
      - tile-server
      - nominatim
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: 127.0.0.1:24224
        tag: backend
        fluentd-async-connect: 'true'
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
      MONGO_INITDB_DATABASE: 'user'
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager

  tile-server:
    container_name: tile-server
    build:
      context: ./docker/
      dockerfile: ./tile-server.Dockerfile
    image: 127.0.0.1:5000/tile-server
    volumes:
      - osm-data:/data/database/
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 201326592 # 192MB
    environment:
      DOWNLOAD_PBF: https://grading.cse356.compas.cs.stonybrook.edu/data/us-northeast.osm.pbf
      THREADS: 2
    deploy:
      placement:
        constraints:
          - node.hostname == tile-server

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.4
    environment:
      PBF_URL: https://grading.cse356.compas.cs.stonybrook.edu/data/us-northeast.osm.pbf
      NOMINATIM_PASSWORD: mysecretpassword
      POSTGRES_SHARED_BUFFERS: 2GB # 25% of total memory
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_AUTOVACUUM_WORK_MEM: 2GB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 4GB
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 4294967296 # half of total memory
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == nominatim

  pgrouting:
    container_name: pgrouting
    image: pgrouting/pgrouting:latest
    volumes:
      - routing-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: routing
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      timeout: 5s
      retries: 10
    deploy:
      placement:
        constraints:
          - node.hostname == router

  db-import:
    build:
      context: ./docker/
      dockerfile: ./db-import.Dockerfile
    container_name: db-import
    volumes:
      - import-data:/data
    restart: 'no'
    depends_on:
      pgrouting:
        condition: service_healthy
    deploy:
      placement:
        constraints:
          - node.hostname == router

volumes:
  osm-data:
  nominatim-data:
  routing-data:
  mongo-data:
  mongo-config:
  import-data:
