networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  osm-data:
  mongo-data:
  mongo-config:
  portainer_data:
  nginx-tile-cache:
  tile-server-cache:

services:
  nginx:
    image: ktao87/cse356:nginx
    ports:
      - '80:80'
    volumes:
      - nginx-tile-cache:/var/cache/tiles
    depends_on:
      - frontend
      - backend
      - search
      - tile-server
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == manager
    logging:
      driver: 'fluentd'
      options:
        tag: nginx
        fluentd-address: fluentd:24224
        fluentd-async-connect: 'true'

  fluentd:
    image: ktao87/cse356:fluentd
    volumes:
      - ./logs/:/var/log/fluentd/
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    deploy:
      placement:
        constraints:
          - node.role == manager

  frontend:
    image: ktao87/cse356:frontend
    depends_on:
      - fluentd
      - backend
      - search
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == manager

  backend:
    image: ktao87/cse356:backend
    depends_on:
      - mongo
    extra_hosts:
      host.docker.internal: host-gateway
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    logging:
      driver: 'fluentd'
      options:
        tag: backend
        fluentd-address: fluentd:24224
        fluentd-async-connect: 'true'

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
      MONGO_INITDB_DATABASE: 'user'
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  tile-server:
    image: ktao87/cse356:tile-server
    volumes:
      - tile-server-cache:/var/cache/tiles
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 7.5GB
        reservations:
          cpus: '4'
          memory: 6GB
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == tile-server

  # Currently trying with file cache
  # tile-cache:
  #   image: bitnami/memcached:latest
  #   environment:
  #     - MEMCACHED_CACHE_SIZE=3500 #in mb
  #     - MEMCACHED_MAX_ITEM_SIZE=31457280 #in bytes
  #     - MEMCACHED_THREADS=2
  #   command: /opt/bitnami/scripts/memcached/run.sh -vv
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.hostname == cache

  search:
    image: ktao87/cse356:search
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  db:
    image: ktao87/cse356:db
    volumes:
      - osm-data:/var/lib/postgresql/14/main
      - /backup:/backup
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2048000000 # 2gb
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 7.5GB
        reservations:
          cpus: '4'
          memory: 6GB
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == db

  agent:
    image: portainer/agent:2.19.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer-ce:2.19.4
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - '9443:9443'
      - '9000:9000'
      - '8000:8000'
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
