networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  osm-data:
  mongo-data:
  mongo-config:
  portainer_data:

services:
  nginx:
    image: ktao87/cse356:nginx
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
      - search
      - tile-server
    deploy:
      placement:
        constraints:
          - node.role == manager
    logging:
      driver: 'fluentd'
      options:
        tag: nginx
        fluentd-address: fluentd:24224
        fluentd-async-connect: 'true'

  fluentd:
    image: ktao87/cse356:fluentd
    volumes:
      - ./logs/:/var/log/fluentd/
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    deploy:
      placement:
        constraints:
          - node.role == manager

  frontend:
    image: ktao87/cse356:frontend
    depends_on:
      - fluentd
      - backend
      - search
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager

  backend:
    image: ktao87/cse356:backend
    depends_on:
      - mongo
    restart: always
    extra_hosts:
      host.docker.internal: host-gateway
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager
    logging:
      driver: 'fluentd'
      options:
        tag: backend
        fluentd-address: fluentd:24224
        fluentd-async-connect: 'true'

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
      MONGO_INITDB_DATABASE: 'user'
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager

  tile-server:
    image: ktao87/cse356:tile-server
    depends_on:
      - db
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == tile-server

  tile-cache:
    image: memcached:latest
    command: '-m 512 -I 10m'
    deploy:
      placement:
        constraints:
          - node.hostname == cache

  search:
    image: ktao87/cse356:search
    depends_on:
      - db
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager

  db:
    image: ktao87/cse356:db
    volumes:
      - osm-data:/var/lib/postgresql/14/main
      - /backup:/backup
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == db

  agent:
    image: portainer/agent:2.19.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer-ce:2.19.4
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - '9443:9443'
      - '9000:9000'
      - '8000:8000'
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
