apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: backend
    spec:
      containers:
        - image: cse356_project-backend:latest
          imagePullPolicy: IfNotPresent
          name: backend
          volumeMounts:
            - mountPath: /app/server.js
              name: backend-hostpath0
            - mountPath: /app/routes
              name: backend-hostpath1
          resources:
            limits:
              cpu: 250m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 75Mi
      restartPolicy: Always
      volumes:
        - hostPath:
            path: ../backend/server.js
          name: backend-hostpath0
        - hostPath:
            path: ../backend/routes
          name: backend-hostpath1
