apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: db-claim1
  name: db-claim1
spec:
  storageClassName: upcloud-block-storage-maxiops
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
