apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: db
    spec:
      containers:
        - image: ktao87/cse356:cse356_project-db
          imagePullPolicy: Always
          name: db
          volumeMounts:
            - mountPath: /var/lib/postgresql/14/main
              name: osm-data
            - mountPath: /backup
              name: db-claim1
          resources:
            limits:
              cpu: 650m
              memory: 4000Mi
            requests:
              cpu: 250m
              memory: 256Mi
      nodeSelector:
        ngroup : three
      restartPolicy: Always
      volumes:
        - name: osm-data
          persistentVolumeClaim:
            claimName: osm-data
        - name: db-claim1
          persistentVolumeClaim:
            claimName: db-claim1
