apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluentd
  name: fluentd
spec:
  ports:
    - name: "24224"
      port: 24224
      targetPort: 24224
    - name: 24224-udp
      port: 24224
      protocol: UDP
      targetPort: 24224
  selector:
    app: fluentd
