apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fluentd
  name: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: fluentd
    spec:
      containers:
        - image: ktao87/cse356:cse356_project-fluentd
          name: fluentd
          ports:
            - containerPort: 24224
              hostPort: 24224
              protocol: TCP
            - containerPort: 24224
              hostPort: 24224
              protocol: UDP
          volumeMounts:
            - mountPath: /fluentd/etc/
              name: fluentd-config
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
            requests:
              memory: "50Mi"
              cpu: "50m"
      restartPolicy: Always
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config
