apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fluentd
  name: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: fluentd
    spec:
      containers:
        - image: cse356_project-fluentd:latest
          imagePullPolicy: IfNotPresent
          name: fluentd
          ports:
            - containerPort: 24224
              hostPort: 24224
              protocol: TCP
            - containerPort: 24224
              hostPort: 24224
              protocol: UDP
          volumeMounts:
            - mountPath: /fluentd/etc/fluent.conf
              name: fluentd-hostpath0
            - mountPath: /var/log/fluentd
              name: fluentd-hostpath1
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
      restartPolicy: Always
      volumes:
        - hostPath:
            path: ../docker/fluent.conf
          name: fluentd-hostpath0
        - hostPath:
            path: ../logs
          name: fluentd-hostpath1
