apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: frontend
    spec:
      containers:
        - image: cse356_project-frontend:latest
          imagePullPolicy: IfNotPresent
          name: frontend
          volumeMounts:
            - mountPath: /app/src
              name: frontend-hostpath0
          resources:
            limits:
              memory: "750Mi"
              cpu: "750m"
            requests:
              memory: "200Mi"
              cpu: "50m"
      restartPolicy: Always
      volumes:
        - hostPath:
            path: ../frontend/src
          name: frontend-hostpath0
