apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: frontend
    spec:
      containers:
        - image: ktao87/cse356:cse356_project-frontend
          name: frontend
          resources:
            limits:
              memory: "500Mi"
              cpu: "150m"
            requests:
              memory: "50Mi"
              cpu: "50m"
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
      restartPolicy: Always