apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: glances
  name: glances
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glances
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: glances
    spec:
      containers:
        - env:
            - name: GLANCES_OPT
              value: -C /glances/conf/glances.conf -w
            - name: TZ
              value: America/New_York
          image: nicolargo/glances:latest-full
          name: glances
          ports:
            - containerPort: 61208
              hostPort: 61208
              protocol: TCP
            - containerPort: 61209
              hostPort: 61209
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: glances-hostpath0
              readOnly: true
          resources:
            limits:
              cpu: 15m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 10Mi
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: glances-hostpath0
