apiVersion: v1
kind: Service
metadata:
  labels:
    app: glances
  name: glances
spec:
  ports:
    - name: "61208"
      port: 61208
      targetPort: 61208
    - name: "61209"
      port: 61209
      targetPort: 61209
  selector:
    app: glances
