apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongo-data
  name: mongo-data
spec:
  storageClassName: upcloud-block-storage-maxiops
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
