apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: mongo:latest
          name: mongo
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
            - mountPath: /data/configdb
              name: mongo-config
          resources:
            limits:
              cpu: 50m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 75Mi
      restartPolicy: Always
      volumes:
        - emptyDir: {}
          name: mongo-data
        - emptyDir: {}
          name: mongo-config
