apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: nginx
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-hostpath0
            - mountPath: /var/run/docker.sock
              name: nginx-hostpath1
          resources:
            limits:
              memory: "50Mi"
              cpu: "250m"
            requests:
              memory: "10Mi"
              cpu: "100m"
      restartPolicy: Always
      volumes:
        - hostPath:
            path: ../docker/nginx.conf
          name: nginx-hostpath0
        - hostPath:
            path: /var/run/docker.sock
          name: nginx-hostpath1
