apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: osm-data
  name: osm-data
spec:
  storageClassName: upcloud-block-storage-maxiops
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
