apiVersion: v1
kind: Service
metadata:
  labels:
    app: portainer
  name: portainer
spec:
  ports:
    - name: "9443"
      port: 9443
      targetPort: 9443
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: portainer
