apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: search
  name: search
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: search
    spec:
      containers:
        - image: ktao87/cse356:cse356_project-search
          name: search-microservice
          ports:
            - containerPort: 80
              hostPort: 3003
              protocol: TCP
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
            requests:
              memory: "50Mi"
              cpu: "50m"
      restartPolicy: Always
