apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tile-server
  name: tile-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tile-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: tile-server
    spec:
      containers:
        - env:
            - name: DOWNLOAD_PBF
              value: https://grading.cse356.compas.cs.stonybrook.edu/data/us-northeast.osm.pbf
          image: cse356_project-tile-server:latest
          imagePullPolicy: IfNotPresent
          name: tile-server
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /data/database
              name: osm-data
          resources:
            limits:
              cpu: 4000m
              memory: 4000Mi
            requests:
              cpu: 10m
              memory: 2000Mi
      restartPolicy: Always
      volumes:
        - emptyDir: {}
          name: osm-data
