apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tile-cache
  name: tile-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tile-cache
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: tile-cache
    spec:
      containers:
        - args:
            - -m
            - "512"
            - -I
            - 10m
            - -v
          image: memcached:latest
          name: tile-cache
          ports:
            - containerPort: 11211
              hostPort: 11211
              protocol: TCP
          resources:
            limits:
              memory: "500Mi"
              cpu: "150m"
            requests:
              memory: "50Mi"
              cpu: "50m"
      restartPolicy: Always
