apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tile-server
  name: tile-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tile-server
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: tile-server
    spec:
      containers:
        - image: ktao87/cse356:cse356_project-tile-server
          imagePullPolicy: Always
          name: tile-server
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "3000Mi"
              cpu: "2000m"
            requests:
              memory: "50Mi"
              cpu: "50m"
      restartPolicy: Always
