apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tile-server
  name: tile-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tile-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        cse356-project-default: "true"
        app: tile-server
    spec:
      containers:
        - env:
            - name: DOWNLOAD_PBF
              value: https://grading.cse356.compas.cs.stonybrook.edu/data/us-northeast.osm.pbf
          image: tile-server
          name: tile-server
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /data/database
              name: osm-data
      restartPolicy: Always
      volumes:
        - name: osm-data
          persistentVolumeClaim:
            claimName: osm-data
