apiVersion: v1
kind: Service
metadata:
  labels:
    app: tile-server
  name: tile-server
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: tile-server
