---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-src
          mountPath: /app/
        resources:
          limits:
            memory: "750Mi"
            cpu: "750m"
          requests:
            memory: "200Mi"
            cpu: "50m"
      volumes:
      - name: frontend-src
        hostPath:
          path: /frontend/
          type: Directory