---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          limits:
            memory: "50Mi"
            cpu: "250m"
          requests:
            memory: "10Mi"
            cpu: "100m"
      volumes:
      - name: nginx-config
        hostPath:
          path: /docker/nginx.conf
          type: File
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  selector:
    app: proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer