{
 "title": "Milestone_3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "sum by (request_time) (rate({app=\"nginx\"} | logfmt [1m]))"
    }
   ]
  },
  { "title": "Tile Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Nginx Error Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=\"nginx\"} | logfmt | status > 400 | line_format `{{.request_id}} -  {{.request}} {{.status}} {{.request_time}}s`"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"milestone_3_tile-server.*\"}[1m])) by (id,name)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}