---
- name: Pre-render tiles
  hosts: tileserver
  tasks:
    - name: get container id
      shell: docker ps | grep "ktao87/cse356:tile-server" | awk '{ print $1 }'
      register: container_id
    - name: kill existing render_list_geo.pl
      shell: |
        pids=$(ps aux | grep '[r]ender_list_geo.pl' | awk '{print $2}')
        if [ -n "$pids" ]; then
          kill -9 $pids
        else
          echo "No process found to kill."
        fi
      ignore_errors: true
    - name: pre-render tiles
      shell: nohup docker exec -i {{ container_id.stdout }} render_list_geo.pl -n 4 -l 4 -x -78.24 -X -71.05 -y 40.39 -Y 43.49 -z 6 -Z 18 -t /var/cache/tiles > /dev/null 2>&1 &